// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

export const SET_SUBSCRIPTION_LIMIT_MESSAGE = 'SET_SUBSCRIPTION_LIMIT_MESSAGE'
export const SET_DEMO_MESSAGE = 'SET_SUBSCRIPTION_LIMIT_MESSAGE'
// export const GET_SUBSCRIPTION_LIMIT_MESSAGE = "GET_SUBSCRIPTION_LIMIT_MESSAGE";

// Operations
export const FETCH_DATA = 'FETCH_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const FETCH_APPINFO = 'FETCH_APPINFO'
export const FETCH_TENANT = 'FETCH_TENANT'

export const SET_SHOW_PLAN = 'SET_SHOW_PLAN'
